### ISSUE TITLE
Duplicates in Common migration steps

### ISSUE THREAD

**Issue by maboerue** [NetAppDocs/ontap-tools-vmware-vsphere-10#24] opened 2024-09-16 08:42 UTC
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/migrate/migrate-to-latest-ontaptools.html

### Page title

Migrate from ONTAP tools for VMware vSphere 9.x to 10.2

### Summary

Please check the “Common migration steps”. I think step 5-8 are duplicates.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment] 2024-09-18 05:06
@maboerue 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment] 2024-09-18 13:04
@maboerue, the issue is fixed now. Thank you for bringing this to our notice.

**Closed by netapp-jani** 2024-09-18 13:04 UTC
